// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4ARs2yRb3z1AaNGTOaVM-wkaRn3nEBVk',
    appId: '1:577742888091:web:8dde07fb5497270e8fba3e',
    messagingSenderId: '577742888091',
    projectId: 'chat-app-1f51f',
    authDomain: 'chat-app-1f51f.firebaseapp.com',
    storageBucket: 'chat-app-1f51f.appspot.com',
    measurementId: 'G-ETM9QYH7YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3sZvoXmef_SOUA_rIebOF9NylzzQ32Sc',
    appId: '1:577742888091:android:683fd48b7a853b318fba3e',
    messagingSenderId: '577742888091',
    projectId: 'chat-app-1f51f',
    storageBucket: 'chat-app-1f51f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDD7Li33jJI6Iw0VjxUwsd0l5pFK5WPyU',
    appId: '1:577742888091:ios:33cb75cdf706023b8fba3e',
    messagingSenderId: '577742888091',
    projectId: 'chat-app-1f51f',
    storageBucket: 'chat-app-1f51f.appspot.com',
    iosClientId: '577742888091-kgmpcal9k5vo4s7d1qb3kobt16koln8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
